second commit3

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -78,14 +78,14 @@ jobs:
         destination_dir: ./  # Deploy to root of gh-pages branch
         keep_files: false   # Clean the branch before deploy
         force_orphan: true  # Use a single commit in gh-pages branch
-    - name: Validate Report Files
-      run: |
-        echo "Report directory contents:"
-        ls -R playwright-report
-        if [ ! -f "playwright-report/index.html" ]; then
-        echo "::error::Missing index.html!"
-        exit 1
-        fi
+    # - name: Validate Report Files
+    #   run: |
+    #     echo "Report directory contents:"
+    #     ls -R playwright-report
+    #     if [ ! -f "playwright-report/index.html" ]; then
+    #     echo "::error::Missing index.html!"
+    #     exit 1
+    #     fi
 
-    - name: Disable Jekyll Processing
+    - name: Disable Jekyll Processing 
       run: touch playwright-report/.nojekyll
